/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WatsonsSystem;

import Cart.CartManager;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ryoji Lagaras
 */
public class CashSuccessfulPurchaseForm extends javax.swing.JFrame {

    /*
    Successful Form if the user selected cash on pickup.
     */
    
    public CashSuccessfulPurchaseForm() {
        initComponents();

    }

    /**
     * Overloaded constructor to initialize form with purchase details.
     *
     * @param cartModel The table model containing cart items.
     */
   
    public CashSuccessfulPurchaseForm(DefaultTableModel cartModel) {
        initComponents(); // Initialize UI components

        // Set the contact number from CartManager
        contact.setText(CartManager.getContactNumber());

        // Set the student number from CartManager
        studentNumber.setText(CartManager.getStudentNumber());

        // Set the purchase date from CartManager
        date.setText(CartManager.getDate());

        // Populate the purchase details using the provided cart model
        setPurchaseDetails(cartModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        studentNumber = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 5));
        ;
        itemField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 5));
        ;
        amountField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(0, 5));
        ;
        quantityField = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Address:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Items Purchased:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 200, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount/s:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantities:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 200, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Number:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 200, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 200, 50));

        contact.setEditable(false);
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setAutoscrolls(false);
        contact.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contact.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        contact.setEnabled(false);
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 180, -1));

        studentNumber.setEditable(false);
        studentNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentNumber.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentNumber.setEnabled(false);
        studentNumber.setOpaque(true);
        studentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNumberActionPerformed(evt);
            }
        });
        jPanel2.add(studentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 180, -1));

        totalField.setEditable(false);
        totalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalField.setAutoscrolls(false);
        totalField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        totalField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalField.setEnabled(false);
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });
        jPanel2.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 413, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 50));

        date.setEditable(false);
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setAutoscrolls(false);
        date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        date.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date.setEnabled(false);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 180, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 20));
        jScrollPane1.setRequestFocusEnabled(false);

        itemField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemField.setBorder(null);
        itemField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        itemField.setEnabled(false);
        itemField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFieldActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(itemField);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 180, 40));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 20));
        jScrollPane2.setRequestFocusEnabled(false);

        amountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountField.setBorder(null);
        amountField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        amountField.setEnabled(false);
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(amountField);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 180, 40));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setFocusable(false);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(0, 20));
        jScrollPane3.setRequestFocusEnabled(false);

        quantityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityField.setBorder(null);
        quantityField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        quantityField.setEnabled(false);
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });
        jScrollPane3.setViewportView(quantityField);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 180, 40));

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel2.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 900, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WATSONSFRAME.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed

    }//GEN-LAST:event_contactActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed

    }//GEN-LAST:event_dateActionPerformed

    private void itemFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFieldActionPerformed

    }//GEN-LAST:event_itemFieldActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        LastFrame lf = new LastFrame();
        lf.show();
        dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    private void studentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNumberActionPerformed

    }//GEN-LAST:event_studentNumberActionPerformed
 /*This method extracts item names, quantities, and prices from the cart,
 formats them into comma-separated lists, and calculates the total amount. */
    public void setPurchaseDetails(DefaultTableModel cartModel) {
    StringBuilder itemsList = new StringBuilder(); // Stores item names
    StringBuilder quantitiesList = new StringBuilder(); // Stores item quantities
    StringBuilder amountsList = new StringBuilder(); // Stores individual prices
    double totalAmount = 0; // Stores the total purchase amount

    // Iterate through cartModel rows to extract purchase details
    for (int i = 0; i < cartModel.getRowCount(); i++) {
        String itemName = cartModel.getValueAt(i, 0).toString(); // Get item name
        int quantity = Integer.parseInt(cartModel.getValueAt(i, 3).toString()); // Get quantity
        double price = Double.parseDouble(cartModel.getValueAt(i, 4).toString()); // Get price per unit
        double total = Double.parseDouble(cartModel.getValueAt(i, 5).toString()); // Get total price

        // Append details to respective lists, separated by commas
        itemsList.append(itemName).append(", ");
        quantitiesList.append(quantity).append(", ");
        amountsList.append("PHP ").append(price).append(", ");
        
        // Accumulate total purchase amount
        totalAmount += total;
    }

    // Remove trailing comma and space from each list if not empty
    if (itemsList.length() > 0) {
        itemsList.setLength(itemsList.length() - 2);
    }
    if (quantitiesList.length() > 0) {
        quantitiesList.setLength(quantitiesList.length() - 2);
    }
    if (amountsList.length() > 0) {
        amountsList.setLength(amountsList.length() - 2);
    }

    // Set formatted text in respective fields
    itemField.setText(itemsList.toString());
    quantityField.setText(quantitiesList.toString());
    amountField.setText(amountsList.toString());
    totalField.setText("PHP " + totalAmount); // Display total price
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashSuccessfulPurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashSuccessfulPurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashSuccessfulPurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashSuccessfulPurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashSuccessfulPurchaseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField date;
    private javax.swing.JTextField itemField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField studentNumber;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
